#!/usr/bin/env pvpython
# -*- coding: utf-8 -*-

'''This is an example post.py script to put in each
   test case. It must use the Book to shuffle info
   to the html presentation.'''

import re,sys,os,string
import matplotlib.pyplot as plt
import numpy
from caseBook import ResultPicture, Book, DataTable
from testSuiteUtils import cleanPostProcessingData


# Read the case database generated by caseManager. It contains
# a Book object. open() uses "pickle".
caseRoot = os.getcwd()
caseBook = Book.open(caseRoot)

# Create ResultPicture object, to store a picture and its info
# It can also store data as shown below (picture1.dataSet)
picture1 = ResultPicture(root=caseRoot,                           \
                         fileName='forces.png',                        \
                         description = 'Viscous force on moving wall')

# Extract arrays for a plot of integrated force
forcesFile=os.path.join(caseRoot,'postProcessing/forces/0/forces.dat')
dataLines = cleanPostProcessingData(forcesFile)
data = []
for item in dataLines:
    data.append(map(float,item.split()))
t = numpy.array(data)[:,0]
f = numpy.array(data)[:,4]

# Add data to picture, optionally
picture1.dataSet=numpy.array([t,f])

# Create an image and save it to disc. The ResultPicture knows the path...
plt.plot(t,f)
plt.grid('on')
plt.savefig(picture1.path())

# Add the picture information to the Book
caseBook.pictures.append(picture1)

# Create some other pictures and add them to the Book as well
# (in this case pure dummies)
picture2 = copy.deepcopy(picture1)
picture2.description = 'Another picture, but same'
caseBook.pictures.append(picture2)
caseBook.pictures.append(picture1)


# Optionally also create some tabular data to present in HTML
# and add these to the book as well.
tableData = []
for row in data[20:25]:
    tableData.append(row[0:4])

table = DataTable(tableData,columnNames=['I','Try','a','data table'])
table.description = 'A random selection of integrated forces'

caseBook.dataTables.append(table)

# Rewrite the Book to disk.
caseBook.close()

